### ISSUE TITLE
fail to build git version

### ISSUE THREAD

**Issue by SilverRainZ** [RicinApp/Ricin#82]
## Summary
- Arch Linux
- ricin-git
- meson 0.30.0

fail to execute `make autogen`:

```
rm -rf ./build
mkdir -p ./build
meson.py . ./build
The Meson build system
Version: 0.30.0
Source dir: /home/la/aur/ricin-git/src/Ricin
Build dir: /home/la/aur/ricin-git/src/Ricin/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: Ricin
Native vala compiler: valac (unknown 0.30.1)
Native c compiler: cc (gcc 5.3.0)
Warning, glib compiled dependencies will not work reliably until this upstream issue is fixed: https://bugzilla.gnome.org/show_bug.cgi?id=745754
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.46.2
Native dependency gio-2.0 found: YES 2.46.2
Native dependency gobject-2.0 found: YES 2.46.2
Native dependency gmodule-2.0 found: YES 2.46.2
Native dependency gtk+-3.0 found: YES 3.18.9
Native dependency libsoup-2.4 found: YES 2.52.2
Native dependency json-glib-1.0 found: YES 1.0.4
Native dependency libnotify found: YES 0.7.6
Native dependency libtoxcore found: YES 0.0.0
Native dependency libconfig found: YES 1.5
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 266, in run
    app.generate()
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 168, in generate
    intr.run()
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1060, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1082, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1076, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1198, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2128, in method_call
    return obj.method_call(method_name, self.flatten(args), kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 796, in method_call
    value = fn(state, args, kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/modules/rpm.py", line 68, in generate_spec_template
    elif isinstance(target, modules.gnome.GirTarget) and target.should_install():
NameError: name 'modules' is not defined
Makefile:14: recipe for target 'autogen' failed
make: *** [autogen] Error 1
```

Can you compile it correctly?
## Additional infos:

BTW: the meson upsteam has changed its script name from `/usr/bin/meson` to `/usr/bin/meson.py`
see mesonbuild/meson#394

**Comment by Sorunome** [comment]
I had the same thing so i manually modified `/usr/lib/python3.5/site-packages/mesonbuild/modules/rpm.py` to look like this http://pastebin.com/wSebf1L0

I forgot to check if there were any meson updates, so yeah, it might have been useless :P

**Comment by SkyzohKey** [comment]
@LastAvenger Hmm, that's a weird issue that seems to be related to your python3 version. Anyway feel free to open the `Makefile` and change `/usr/bin/meson` to `/usr/bin/meson.py`. I should probably do some tests to execute the correct path to meson, in order to avoid these weird issues. I'll investigate.

Anyway did @Sorunome solved your issue ?

**Comment by SilverRainZ** [comment]
hmm, my python version is 3.5.1, and I still failed to build it.
issues/
@Sorunome I don't want to modified meson's code, because I am maintaining the package of ricin,
I shouldn't let ricin requires a patched meson. 

any way to avoid this issue? mesonbuild/meson#498

**Comment by Sorunome** [comment]
I am actually thinking it's a bug in meson as they do `from ..modules import gnome` and then later on `isinstance(target, modules.gnome.GirTarget)` instead of `isinstance(target, gnome.GirTarget)`

**Comment by SkyzohKey** [comment]
@LastAvenger @Sorunome Bug have been fixed, just compile from the latest trunk from meson ;)
